FROM node:22-alpine

RUN apk add --no-cache python3 make g++ bash

WORKDIR /app

COPY package*.json ./

# RUN npm install --include=dev
RUN npm install --include=dev --legacy-peer-deps
# RUN NODE_ENV=development npm install
COPY tsconfig.json ./
# RUN echo "ts-node-dev contents:" && ls -la node_modules/ts-node-dev

COPY . .

# Port exposed in docker-compose.yml, which references server/.env

CMD ["npm", "run", "dev"]
# CMD [ "sh", "-c", "echo 'Running Dockerfile.dev'; npm run dev" ]