FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --include=dev
COPY tsconfig.json .
RUN echo "ts-node-dev contents:" && ls -la node_modules/ts-node-dev

COPY . .

# Port exposed in docker-compose.yml, which references server/.env

CMD ["npm", "run", "dev"]
# CMD [ "sh", "-c", "echo 'Running Dockerfile.dev'; npm run dev" ]